name: Exchange info
on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        working-directory: ./scrape
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        working-directory: ./scrape
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        working-directory: ./scrape
        run: |
          pnpm install
          pnpm playwright install chromium

      - name: Run script
        working-directory: ./scrape
        run: pnpm run scrape

      - name: Commit and push changes
        working-directory: ./scrape
        run: |
          git config --global user.name "[bot] Exchange info"
          git config --global user.email "bot@exchanges-info.com"
          git add .
          git commit -m "Update exchange info"
          git push
